# Generated by Django 2.1.4 on 2019-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('intersex', 'Intersex'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=8, null=True),
        ),
    ]
