# Generated by Django 2.1.4 on 2019-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0003_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(
                choices=[('female', 'Female'), ('interses', 'Intersex'), ('male', 'Male'), ('unknown', 'Unknown')],
                max_length=8, null=True),
        ),
    ]
